---
- name: Configure Fedora workstation
  hosts: local
  become: true

  tasks:
    - name: Install pipx
      dnf:
        name: pipx
        state: present

    - name: Install gphotos-sync via pipx
      become: false
      command: pipx install gphotos-sync
      args:
        creates: ~/.local/bin/gphotos-sync
