---
- name: Configure Fedora workstation
  hosts: local
  become: true

  tasks:
    - name: Install Brave browser
      shell: curl -fsS https://dl.brave.com/install.sh | sh
      args:
        creates: /usr/bin/brave-browser
